on:
  push:
    branches:
      - master
  pull_request:
name: Test
jobs:
  test:
    strategy:
      matrix:
        # os: [ubuntu-latest, macos-latest, windows-latest]
        os: [macos-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Install Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.18.x

      - name: Checkout code
        uses: actions/checkout@v3

      - name: Restore Cache
        uses: actions/cache@v3
        with:
          path: ~/go/pkg/mod
          key: ${{ runner.os }}-v1-go-${{ hashFiles('**/go.sum') }}

      - name: Test
        run: go test -race -covermode=atomic -coverprofile="profile.cov" ./...

      # - name: Coveralls
      #   if: matrix.os == 'ubuntu-latest'
      #   uses: shogo82148/actions-goveralls@v1
      #   with:
      #     path-to-profile: profile.cov
